// <auto-generated />
namespace Business.DomainClasses.S00210326.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Changingnametonospaces : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changingnametonospaces));
        
        string IMigrationMetadata.Id
        {
            get { return "202301021907070_Changing name to no spaces"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
